"""Add abbreviation column to Team model

Revision ID: 3cdd85480a7a
Revises: eaba3958a0f1
Create Date: 2023-10-19 22:55:17.615991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cdd85480a7a'
down_revision = 'eaba3958a0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abbreviation', sa.String(length=10), nullable=True))
        batch_op.drop_column('xg')
        batch_op.drop_column('xg_conceded')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xg_conceded', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('xg', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('abbreviation')

    # ### end Alembic commands ###
