"""Add CurrentGameweek model

Revision ID: eaba3958a0f1
Revises: ea4c4ad61ebf
Create Date: 2023-10-19 14:40:04.640496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaba3958a0f1'
down_revision = 'ea4c4ad61ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_gameweek',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gameweek_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_gameweek')
    # ### end Alembic commands ###
